### ISSUE TITLE
I wanna help with Spanish Translation

### ISSUE THREAD

**Issue by jrab66** [centreon/centreon-translations#1]
Hi, i wanna know how to help to centreon translation.

**Comment by lpinsivy** [comment]
Hi,

You can find help using new README : https://github.com/centreon/centreon-translations/blob/2.7/README.md

If you need more information do not hesitate to contact me.

Regards,

**Comment by jrab66** [comment]
I wanna try to help when i have some spare time, greetings from el salvador.

2016-03-30 10:26 GMT-06:00 Laurent Pinsivy notifications@github.com:

> Closed #1 https://github.com/centreon/centreon-translations/issues/1.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/centreon/centreon-translations/issues/1#event-608531097

## 

José Barahona.
