### ISSUE TITLE
Project translation into portuguese

### ISSUE THREAD

**Issue by sujeiitosuspeito** [centreon/centreon-translations#2]
Good Morning,

I would like to start a translation project from the web center into the language of Portuguese Brazil,

I wait and thank you.

**Comment by sujeiitosuspeito** [comment]
Can someone help?

**Comment by ganoze** [comment]
The _centreon-translations_ project is now deprecated and translations are directly available within the [centreon project](https://github.com/centreon/centreon). You will find Portuguese Brazil translations there.
