### ISSUE TITLE
[Centreon-Web] - Business Activity - More action menu not translated

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-translations#4]
Hi,

In centreon-web 2.8.16, the more action menu in Monitoring-> Business Activity -> Supervision is not translated. see below.
![image](https://user-images.githubusercontent.com/8720203/37220272-69a62c54-23c6-11e8-8152-3c37e467930e.png)

Regards,

**Comment by ganoze** [comment]
The _centreon-translations_ project is now deprecated. Translations are directly available within the [centreon project](https://github.com/centreon/centreon). Feel free to open an issue there if your bug still applies.
